#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void usage(void) {
  fprintf(stderr, "usage: nprt-doc <output-dir>\n");
}

int main(int argc, char** argv) {
  if (argc < 2) { usage(); return 2; }
  char path[1024];
  snprintf(path, sizeof(path), "%s/index.html", argv[1]);
  FILE* f = fopen(path, "wb");
  if (!f) {
    fprintf(stderr, "nprt-doc: failed to write %s\n", path);
    return 1;
  }
  fprintf(f, "<!doctype html><html><head><meta charset='utf-8'><title>Nullprt API</title></head><body>");
  fprintf(f, "<h1>Nullprt API Reference</h1>");
  fprintf(f, "<p>Generated by nprt-doc.</p>");
  fprintf(f, "<h2>Ethical Use Warning</h2>");
  fprintf(f, "<p>High-risk APIs are for authorized security research and compatibility testing only.</p>");
  fprintf(f, "</body></html>");
  fclose(f);
  return 0;
}
